---
name: shellwords
version: '0.1.2.2'
synopsis: Parse strings into words, like a shell would
description: See https://github.com/pbrisbin/hs-shellwords#readme
category: Text
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2018 Patrick Brisbin
license: MIT
github: pbrisbin/hs-shellwords
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && <5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - megaparsec >= 7.0.0
    - text

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - shellwords
