---
version: 2.0

jobs:
  build:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    environment:
      STACK_ARGUMENTS: --no-terminal
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}-
            - v1-master-
      - run:
          name: Dependencies
          command: make setup setup.lint setup.coverage
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: |
            curl -L -o .hlint.yaml \
              https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
            make lint
      - run:
          name: Test
          command: make test coverage.report
