---
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v0-{{ .Branch }}-{{ checksum "digest" }}
            - v0-{{ .Branch }}-
            - v0-master-
      - run:
          name: Dependencies
          command: make setup setup.lint setup.coverage
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v0-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Lint
          command: |
            curl -L -o .hlint.yaml \
              https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
            make lint
      - run:
          name: Test
          command: |
            make test
            tix2cc | ./cc-test-reporter upload-coverage --input -
